---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bns-reference
  namespace: default
  labels:
    app: bns-reference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bns-reference
  template:
    metadata:
      labels:
        app: bns-reference
    spec:
      containers:
      - name: bns-reference
        image: 79.137.37.94:8082/bnsref:1.0.0
        ports:
        - containerPort: 8044  # Hardcode based on BACK_SERVER_PORT from your input
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: BACK_SPRING_APPLICATION_NAME
        - name: SPRING_CLOUD_CONFIG_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: BACK_SERVER_URI
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: BACK_SPRING_CONFIG_IMPORT
        - name: SPRING_CLOUD_CONFIG_ENABLED
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: BACK_SPRING_CLOUD_CONFIG_ENABLED
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: BACK_INSTANCE_PREFER_IP_ADDRESS
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: BACK_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: EUREKA_INSTANCE_INSTANCE_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: BACK_INSTANCE_INSTANCE_ID
