---
apiVersion: v1
kind: Service
metadata:
  name: bns-reference
  namespace: default
spec:
  selector:
    app: bns-reference
  ports:
  - protocol: TCP
    port: 8044  # Matches containerPort
    targetPort: 8044
  type: ClusterIP
