---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: default
spec:
  selector:
    app: config-server
  ports:
  - protocol: TCP
    port: 8888  # Internal port within the cluster
    targetPort: 8888  # Matches containerPort
    nodePort: 32002  # External port on nodes
  type: NodePort
