---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: default
spec:
  selector:
    app: config-server
  ports:
  - protocol: TCP
    port: 8888  # Matches containerPort
    targetPort: 8888
  type: ClusterIP
