---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: default
spec:
  selector:
    app: eureka-server
  ports:
  - protocol: TCP
    port: ${DISCOVERY_SERVER_PORT}
    targetPort: ${DISCOVERY_SERVER_PORT}
  type: ClusterIP
