---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: bns-app
spec:
  selector:
    app: eureka-server
  ports:
  - protocol: TCP
    port: 8761  # Internal port within the cluster
    targetPort: 8761  # Matches containerPort from Deployment
    nodePort: 32005  # External port on nodes
  type: NodePort
