---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: default
spec:
  selector:
    app: eureka-server
  ports:
  - protocol: TCP
    port: 8761  # Matches containerPort from Deployment
    targetPort: 8761
  type: ClusterIP
