---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: ${ANGULAR_PORT}
    targetPort: 80
  type: ClusterIP
