---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker-repo:8082/angular-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "${API_URL}"
