---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 4200  # Matches containerPort
    targetPort: 4200
  type: NodePort
