apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 79.137.37.94:8082/pfe-frontend:1.0.0
        ports:
        - containerPort: 80  # Updated to match Nginx listen port
        env:
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_URL
