apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80  # Internal port within the cluster
    targetPort: 80  # Matches containerPort
    nodePort: 32000  # External port on nodes
  type: NodePort
