---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 9999  # Matches containerPort
    targetPort: 9999
  type: ClusterIP
