---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: bns-app
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 9999  # Internal port within the cluster
    targetPort: 9999  # Matches containerPort
    nodePort: 32003  # External port on nodes
  type: NodePort
