---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 79.137.37.94:8082/gateway-service:1.0.0
        ports:
        - containerPort: 9999  # Hardcode based on GATEWAY_SERVER_PORT
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GATEWAY_APPLICATION_NAME
        - name: SERVER_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GATEWAY_SERVER_PORT
        - name: SPRING_CLOUD_DISCOVERY_ENABLED
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GATEWAY_SPRING_CLOUD_DISCOVERY_ENABLED
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GATEWAY_INSTANCE_PREFER_IP_ADDRESS
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GATEWAY_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: EUREKA_INSTANCE_INSTANCE_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GATEWAY_INSTANCE_INSTANCE_ID
        - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GATEWAY_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
        - name: SPRING_CLOUD_CONFIG_ENABLED
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GATEWAY_SPRING_CLOUD_CONFIG_ENABLED
        livenessProbe:
          httpGet:
            path: /eureka
            port: 9999  # Hardcode to match containerPort
          initialDelaySeconds: 30
          periodSeconds: 10
