apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
spec:
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: ${KEYCLOAK_PORT}
    targetPort: 8085
  type: ClusterIP
