---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.1.3
        ports:
        - containerPort: 8085
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: KEYCLOAK_ADMIN_USER
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: KC_HTTP_PORT
          value: "8085"
        command: ["start-dev", "--http-port=8085", "--import-realm"]
        volumeMounts:
        - name: keycloak-config
          mountPath: /opt/keycloak/data/import
      volumes:
      - name: keycloak-config
        configMap:
          name: keycloak-realm-config
