---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432  # Matches containerPort
    targetPort: 5432
  type: ClusterIP
